#!/usr/bin/env node
require('app-module-path').addPath(__dirname + '/');
var cluster = require('cluster');
var os = require('os');

if (cluster.isMaster) {
// Spawn as many workers as there are CPUs in the system.
    for (var i = 0, n = os.cpus().length; i < n; i += 1)
        cluster.fork();

    cluster.on('exit', function (worker, code, signal) {
        console.log('worker ' + worker.process.pid + ' died');
    });
} else {
    require('app');
}
